### ISSUE TITLE
500 Internal Server Error: parse-node-version

### ISSUE THREAD

**Issue by rerime** [gulpjs/parse-node-version#1]
Related issue
https://developercommunity.visualstudio.com/content/problem/396176/npm-package-install-failure-microsoftvisualstudios.html?childToView=399670

```npm install parse-node-version --verbose
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'install',
npm verb cli   'parse-node-version',
npm verb cli   '--verbose' ]
npm info using npm@6.4.1
npm info using node@v11.3.0
npm verb config Skipping project config: 
npm verb npm-session 92cbacb13e1680c1
npm http fetch GET 500 https://tfs/hq/_packaging/test-web/npm/registry/parse-node-version 70687ms attempt #3
npm timing stage:rollbackFailedOptional Completed in 0ms
npm timing stage:runTopLevelLifecycles Completed in 71233ms
npm verb stack Error: 500 Internal Server Error: parse-node-version@latest
npm verb stack     at fetch.then.res (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
npm verb stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_
modules\bluebird\js\release\util.js:16:23)
npm verb stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
npm verb stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
npm verb stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
npm verb stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
npm verb stack     at Async._drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
npm verb stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
npm verb stack     at Immediate.Async.drainQueues [as _onImmediate] (C:\ProgramFiles\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
npm verb stack     at processImmediate (timers.js:632:19)
npm verb cwd C:\Users\user
npm verb Windows_NT 6.3.9600
npm verb argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "parse-node-version" "--verbose"
npm verb node v11.3.0
npm verb npm  v6.4.1
npm ERR! code E500
npm ERR! 500 Internal Server Error: parse-node-version@latest
npm verb exit [ 1, true ]
npm timing npm Completed in 72187ms

npm ERR! A complete log of this run can be found in:
```

**Comment by phated** [comment]
You are not using the public npm registry.
